### ISSUE TITLE
OOtW no longer compatible with other DeCiv mods due to Plastics

### ISSUE THREAD

**Issue by carriontrooper** [the-s-is-silent/Outlaws-of-the-Wastes#12]
What it says on the tin - due to Plastics being replaced with Synthetic Materials, other DeCiv mods that refer to Plastics are no longer compatible.

Perhaps, considering that the difference between Plastics and Synthetic Materials are but a name and quote change, it would be better to use the English translation file to change those 2 strings instead of taking out Plastics entirely. I'll make a PR soon.

**Comment by the-s-is-silent** [comment]
TBH, the replacement of the techs was deliberate - as I noted in the extensions channel on the DeCiv Discord server, this is intended as the preliminary step towards the addition of new techs. However, I will accept your advice to undo that step and simply use the Translations files to rename the base scenario's techs/quotes.

**Comment by the-s-is-silent** [comment]
However, using the translation route also affects the Plastics resource, which was absolutely not intended. So...time to look over all of the other expansion mods and find where the tech replacement breaks them
